### ISSUE TITLE
[Bug] ZXingAutofocusScannerView.java error: getParameters failed

### ISSUE THREAD

**Issue by luckv** [mono0926/barcode_scan2#32] opened 2021-09-22 14:33 UTC
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add the verbose output of `flutter run`.

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [ ] Android? Version: ...
 - [ ] Real Device? Which?: ...
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan`
 - Output of `flutter --version`:
```
Flutter ...
```

**Additional context**

**Comment by mono0926** [comment] 2021-09-22 21:17
Duplicate of #33

**Closed by mono0926** 2021-09-22 21:17 UTC
Labels: bug
